# Generated by Django 3.0.5 on 2020-05-25 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='team_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
